name: Deploy Spring Boot to AWS Lightsail

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK 17 설치
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      
      # application.properties 파일 생성
      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION }}" > ./application.properties
        shell: bash

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker build -t ${{ secrets.DOCKER_REPO }}:spring .
          docker push ${{ secrets.DOCKER_REPO }}:spring

      # Lightsail 서버에 SSH로 접속해 Docker 이미지 배포
      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_REPO }}:spring
            docker stop spring1 || true
            docker rm spring1 || true
            docker run -d --name spring1 -p 8080:8080 ${{ secrets.DOCKER_REPO }}:spring
